version: '3'

services:
  clientbox:
    build: 
      context: .
      dockerfile: Dockerfile.clientbox
    image: genesys_clientbox:latest
    volumes:
      - ./:/home/connect

  serverbox:
    build:   
      context: .
      dockerfile: Dockerfile.serverbox
    image: genesys_serverbox:latest
    environment:
      - TESTVAR=${TESTVAR}
    volumes:
      - ./:/home/connect



