FROM ubuntu:18.04

RUN mkdir /test && \
    mkdir /home/connect && \
    apt-get update && \
    apt-get install -y python3 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
  
COPY script.sh script.py /test/

WORKDIR /test

CMD ./script.sh
